name: appplatform-openfaas
region: ams3
services:
- build_command: curl -sLOS https://github.com/openfaas/faas-cli/releases/download/0.12.9/faas-cli > faas-cli &&  chmod +x faas-cli && faas-cli build --shrinkwrap -f stack.yml && find .
  github:
    branch: master
    deploy_on_push: true
    repo: alexellis/appplatform-openfaas
  instance_count: 1
  source_dir: build/webhook-audit
  instance_size_slug: professional-xs
  name: appplatform-openfaas
  routes:
  - path: /

